config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'search/result'

  get 'about/index'
  resources :contacts
  
  get 'map/index'
  get 'map/traker'
  resources :turtle_data

  get 'home/index'
  root 'home#index'


  # resources :home
  resources :chart do
    collection do
      get '/', to: 'chart#index', as: 'analysis'
      # post '/analysis/:analysis_id', to: 'chart#analysis'
      get '/analysis/:analysis_id', to: 'chart#analysis'
    end
  end

  resources :map
  resources :users
  resources :turtles
  resources :turtle_data
  resources :sessions

  get 'map/turtle_info/:id',controller: 'turtles', action: 'turtle_info', as: 'turtle_info'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  get 'home', to: 'home#index', as: 'home'
  # get 'chart', to: 'chart#chart', as: 'chart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # load_turtles
    @turtles = Turtle.all
    @users = User.all
    @turtleDatas = TurtleDatum.all
  end

  # def load_turtles  
  #   @turtles_default = Gmaps4rails.build_markers(Turtles.all) do |plot, marker|  
  #      marker.lat plot.latitude  
  #      marker.lng plot.longitude  

  #      @status = rand(1..4)  
  #      @battery = rand(10..90)  
  #      @ip = "192.168."+rand(0..255).to_s+"."+rand(15..250).to_s  
  #      @connected = rand(50..100)  

  #      if @status == 1  
  #        url_alert = "/good.png"  
  #        @status == "Normal"  
  #      else  
  #        url_alert = "/alert.png"  
  #      end  

  #      marker.picture({  
  #        "url" => url_alert,  
  #        "width" => 35,  
  #        "height" => 30  
  #      })  

  #      marker.infowindow render_to_string(:partial => "/turtles/info",   
  #        :locals => {:name => plot.name, :battery => @battery, :date => rand(6.months.ago..Time.now), :ip => @ip, :connected => @connected })  
  #   end  
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<br/>
<h1 class="display-3 text-dark text-center">Internet <i class="fa fa-globe-americas fa-1x"></i>f Turtles </h1>
<br/>
<br/>
<div class="text-dark row justify-content-md-center">
  <div class="card col-md-auto" style="width: 400px ;margin: 10px;">
    <%= image_tag("turtleMain.jpg", :class => "img-thumbnail", :style => "") %>
    <div class="card-body">
      <!--    <h5 class="card-title">Card title</h5>-->
      <h2>Get to know us:</h2>
      <div class="row text-center">
        <div class="col">
          <div class="counter">
            <a class="text-info" href=<%= turtles_path %>>
              <i class="fa fa-search-location fa-1x"></i>
              <h2 class="timer count-title count-number"><%= @turtles.length %></h2>
              <p class="count-text ">Turtles tracked</p></a>
          </div>
        </div>
        <div class="col">
          <div class="counter">
            <a class="text-info" href=<%= users_path %>>
              <i class="fa fa-user-friends fa-1x"></i>
              <h2 class="timer count-title count-number"><%= @users.length %></h2>
              <p class="count-text ">Users registered</p></a>
          </div>
        </div>
        <div class="col">
          <div class="counter">
            <a class="text-info" href=<%= turtle_data_path %>>
              <i class="fa fa-database fa-1x"></i>
              <h2 class="timer count-title count-number"><%= @turtleDatas.length %></h2>
              <p class="count-text ">Turtle datum stored</p></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div style="margin-right: 30px" class="col">
    <br/>
    <h2 class="text-justify ">
      Internet of Turtles – or IoT, as we call it – is a research project on Internet of Things and Swarm
      Intelligence aimed to track, monitor and thus contribute to the protection of endangered sea
      turtles all around the world. <br/></h2>
    <br/>
    <div class="row justify-content-md-center">
      <div class="col"><h2 class="text-justify">
        To do that our team is developing low-cost electronic modules
        capable of acquiring geolocation and forming decentralized communication networks.
        <!-- Internet of Turtles is a successful project to track sea turtle species.
        Using swarm concepts, turtles can share data with each other. This way we can get data from your location even if the turtle in question does not appear in the data collection base. -->
        <!-- <br/>You can check in the left our achievements and by clicking on icon, you can view our data. -->
      </h2></div>
      <div class="col-md-auto">
        <figure class="figure">
          <%= image_tag("photos/Module_Virtual_Prototype.png", :class => "img-thumbnail", :style => "width:400px") %>
          <figcaption><b>Module Virtual Prototype.</b></figcaption>
        </figure>
      </div>
    </div>
  </div>
</div>
<br/>
<br/>
<h2>Our project history in images.</h2>
<br/>
<div class="row justify-content-md-center">

  <br/>
  <div class="col-md-auto">
    <figure class="figure">
      <%= image_tag("photos/Module_v_1.jpg", :class => "img-thumbnail", :style => "height: 300px") %>
      <figcaption><b>Module v1.0.</b></figcaption>
    </figure>
  </div>
  <div class="col-md-auto">
    <figure class="figure">
      <%= image_tag("photos/Module_with_base.jpg", :class => "img-thumbnail", :style => "height: 300px") %>
      <figcaption><b>Module and base.</b></figcaption>
    </figure>
  </div>
  <div class="col-md-auto">
    <figure class="figure">
      <%= image_tag("photos/Installing_the_module.jpg", :class => "img-thumbnail", :style => "height: 300px") %>
      <figcaption><b>Installing the Module.</b></figcaption>
    </figure>
  </div>

</div>
<div class="row justify-content-md-center">

  <br/>
  <div class="col-md-auto">
    <figure class="figure ht">
      <%= image_tag("photos/Module_deployed.jpg", :class => "img-thumbnail", :style => "height: 300px") %>
      <figcaption><b>Module deployed and ready to track!</b></figcaption>
    </figure>
  </div>
  <div class="col-md-auto">
    <figure class="figure">
      <%= image_tag("photos/Ready_to_track.jpg", :class => "img-thumbnail", :style => "height: 300px") %>
      <figcaption><b>Module deployed and ready to track!</b></figcaption>
    </figure>
  </div>


</div>