config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'search/result'

  get 'about/index'
  resources :contacts
  
  get 'map/index'
  get 'map/traker'
  resources :turtle_data

  get 'home/index'
  root 'home#index'


  # resources :home
  resources :chart do
    collection do
      get '/', to: 'chart#index', as: 'analysis'
      # post '/analysis/:analysis_id', to: 'chart#analysis'
      get '/analysis/:analysis_id', to: 'chart#analysis'
    end
  end

  resources :map
  resources :users
  resources :turtles
  resources :turtle_data
  resources :sessions

  get 'map/turtle_info/:id',controller: 'turtles', action: 'turtle_info', as: 'turtle_info'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  get 'home', to: 'home#index', as: 'home'
  # get 'chart', to: 'chart#chart', as: 'chart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/turtle.rb
class Turtle < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    # validates :user_id, presence: true
    validates :species, presence: true

    belongs_to :user
    has_many :turtle_data, dependent: :destroy

    def self.search(search)
        if search.present?
            Turtle.where('name LIKE ?', "%#{search}%")
        else
            Turtle.all
        end
      end  
end

app/controllers/turtles_controller.rb
class TurtlesController < ApplicationController
  before_action :set_turtle, only: [:show, :edit, :update, :destroy]

  # GET /turtles
  # GET /turtles.json
  def index
    @turtles = Turtle.all
    
  end

  # GET /turtles/1
  # GET /turtles/1.json
  def show
  end

  # GET /turtles/new
  def new
    if !current_user
      redirect_to home_path
    else
      @turtle = Turtle.new
    end
  end

  # GET /turtles/1/edit
  def edit
    if current_user != @turtle.user
      redirect_to @turtle
    end
  end

  # POST /turtles
  # POST /turtles.json
  def create
    if !current_user
      redirect_to home_path
    else
      @turtle = Turtle.new(turtle_params)
      if super_user  
        user = User.find(turtle_params[:user_id])
      else if not current_user.nil?
        @turtle.user_id = current_user.id
        puts "------------------debug --------------------"
        puts current_user.id
        puts @turtle.user_id
        user = current_user
        # @turtle.researcher = User.find(current_user.id)
          end
      end
      
      respond_to do |format|
        
        if @turtle.save
          format.html { redirect_to @turtle, notice: 'Turtle was successfully created.' }
          format.json { render :show, status: :created, location: @turtle }
        else
          format.html { render :new }
          format.json { render json: @turtle.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  # PATCH/PUT /turtles/1
  # PATCH/PUT /turtles/1.json
  def update
    respond_to do |format|
      if @turtle.update(turtle_params)
        format.html { redirect_to @turtle, notice: 'Turtle was successfully updated.' }
        format.json { render :show, status: :ok, location: @turtle }
      else
        format.html { render :edit }
        format.json { render json: @turtle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turtles/1
  # DELETE /turtles/1.json
  def destroy
    if !current_user
      redirect_to home_path
    else  
      @turtle.destroy
      respond_to do |format|
        format.html { redirect_to turtles_url, notice: 'Turtle was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def turtle_info

    @turtle = Turtle.all.find(params[:id])
    respond_to do |format|
      # format.html { redirect_to @turtle, notice: 'Turtle was successfully created.' }
      format.html { render partial: 'turtle_info'}
      format.json { render :json => @turtle.turtle_data}
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_turtle
    @turtle = Turtle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def turtle_params
    params.require(:turtle).permit(:name, :sex, :species, :fixation_date, :birthday, :description, :user_id)
  end
end

app/helpers/turtles_helper.rb
module TurtlesHelper
end

app/views/turtles/_form.html.erb
<%= form_with(model: turtle, local: true) do |form| %>
  <% if turtle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turtle.errors.count, "error") %> prohibited this turtle from being saved:</h2>

      <ul>
        <% turtle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control",:required => true %>
  </div>

  <div class="form-group">
    <%= form.label :sex %>
    <%= form.select :sex, ['', 'Male', 'Female', 'Other'], {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :species %>
    <%= form.select :species, ['Loggerhead', 'Green turtle', 'Leatherback', 'Hawksbill', 'Kemp\'s ridley', 'Olive ridley', 'Flatback'],{}, {class: "form-control"}%>
  </div>

  <div class="form-group">
    <%= form.label :fixation_date %>
    <br/>
    <%= form.datetime_select :fixation_date,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :birthday %>
    <br/>
    <%= form.datetime_select :birthday,class: "form-control"  %>
  </div>
  <%#= User.all.select(:id).to_a.uniq { |p| p.id } %>
<!--  </br>-->
  <%#= User.all.collect { |user| [user.name, user.id] } %>
  <% if super_user %>
    <div class="form-group">
      <%= form.label :user_id %>
      <br/>
      <%= form.select :user_id, User.all.collect { |user| [user.name, user.id] }, {}, {class: "form-control"} %>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description,class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class: 'btn btn-success form-control' %>
  </div>
<% end %>

app/views/turtles/_form2.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @turtle.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @turtle.sex %>
</p>

<p>
  <strong>Species:</strong>
  <%= @turtle.species %>
</p>

<p>
  <strong>Fixation date:</strong>
  <%= @turtle.fixation_date %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @turtle.birthday %>
</p>

<p>
  <strong>Researcher:</strong>
</p>

<p>
  <strong>Description:</strong>
  <%= @turtle.description %>
</p>
<% if @turtle.user_id == current_user.id || super_user %>
<%= link_to 'Edit', edit_turtle_path(@turtle) %> |
<% end %>

<%= link_to 'Back', turtles_path %>

app/views/turtles/_table.html.erb
<table class="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Sex</th>
    <th scope="col">Species</th>
    <th scope="col">Fixation date</th>
    <th scope="col">Birthday</th>
    <th scope="col">Researcher</th>
    <th scope="col">Description</th>
    <th scope="col" colspan="1">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @turtles.each do |turtle| %>
    <tr>
      <th scope="row"><%= turtle.name %></th>
      <td><%= turtle.sex %></td>
      <td><%= turtle.species %></td>
      <td><%= turtle.fixation_date %></td>
      <td><%= turtle.birthday %></td>
      <td><%= turtle.user.name %></td>
      <td><%= turtle.description %></td>
      <td><%= link_to 'Show', turtle, class: "btn btn-info btn-sm " %>
        <% if turtle.user == current_user || super_user %>
          |
          <%= link_to 'Edit', edit_turtle_path(turtle), class: "btn btn-primary btn-sm " %> |
          <%= link_to 'Destroy', turtle, class: "btn btn-danger btn-sm ", method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/turtles/_turtle_info.html.erb
<div class="col-md-auto">
<h5 class="text-center">Turtle Informations</h5>
  <%= form_with model: @turtle do |form| %>
    <fieldset disabled>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :sex %>
        <%= form.select :sex, ['', 'Male', 'Female', 'Other'], {}, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= form.label :species %>
        <%= form.select :species, ['Loggerhead', 'Green turtle', 'Leatherback', 'Hawksbill', 'Kemp\'s ridley', 'Olive ridley', 'Flatback'], {}, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= form.label :fixation_date %>
        <br/>
        <%= form.datetime_select :fixation_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :birthday %>
        <br/>
        <%= form.datetime_select :birthday, class: "form-control" %>
      </div>
    </fieldset>

    <div class="form-group">
      <%= form.label :user_id %>
      <%= link_to @turtle.user.name, user_path(@turtle.user_id), class: 'btn btn-light form-control' %>
    </div>
    <fieldset disabled>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>
    </fieldset>
  <% end %>
  <br/></div>

app/views/turtles/edit.html.erb
<div class="form-mine">
  <h1 class="display-4 text-center"><b>Editing Turtle</b></h1>

  <%= render 'form', turtle: @turtle %>
  <br/>
  <div class="form-group">
    <%= link_to 'View', @turtle, class: "btn btn-info form-control" %>
    <br/>
    <br/>
    <%= link_to 'Back', turtles_path, class: "btn btn-light form-control" %>
  </div>
</div>

app/views/turtles/index.html.erb
<h1 class="display-4 text-center">Turtles</h1>
<br/>

<%= render partial: 'table' %>
<br>

<% if current_user %>
  <div class="form-mine">
    <%= link_to 'New Turtle', new_turtle_path, class: "btn btn-success form-control" %>
  </div>
<% else %>
  <!-- <script type="text/javascript">
  window.location = "<%= home_path %>";
</script> -->
<% end %>

app/views/turtles/new.html.erb
<div class="form-mine">
<% if current_user %>
    <h1 class="display-4 text-center"><b>New Turtle</b></h1>

  <%= render 'form', turtle: @turtle %>
    <br/>
  <%= link_to 'Back', turtles_path, class: "btn btn-light   form-control" %>

<% else %>
  <script type="text/javascript">
      window.location = "<%= home_path %>";
  </script>
<% end %>
</div>

app/views/turtles/show.html.erb
<div class="form-mine">
  <h1 class="display-4 text-center"><b>Show Turtle</b></h1>
  <%= form_with model: @turtle do |form| %>
    <fieldset disabled>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :sex %>
        <%= form.select :sex, ['', 'Male', 'Female', 'Other'], {}, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= form.label :species %>
        <%= form.select :species, ['Loggerhead', 'Green turtle', 'Leatherback', 'Hawksbill', 'Kemp\'s ridley', 'Olive ridley', 'Flatback'], {}, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= form.label :fixation_date %>
        <br/>
        <%= form.datetime_select :fixation_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :birthday %>
        <br/>
        <%= form.datetime_select :birthday, class: "form-control" %>
      </div>
    </fieldset>

    <div class="form-group">
      <%= form.label :user_id %>
      <%= link_to @turtle.user.name, user_path(@turtle.user_id), class: 'btn btn-light form-control' %>
    </div>
    <fieldset disabled>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>
    </fieldset>
  <% end %>
  <br/>


  <% if not current_user.nil? %>
    <% if @turtle.user_id == current_user.id || super_user %>
      <%= link_to 'Edit', edit_turtle_path(@turtle), class: 'btn btn-primary form-control' %>
      <br/>
      <br/>
    <% end %>
  <% end %>


  <%= link_to 'Show turtles', turtles_path, class: 'btn btn-light form-control' %>
</div>