config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'search/result'

  get 'about/index'
  resources :contacts
  
  get 'map/index'
  get 'map/traker'
  resources :turtle_data

  get 'home/index'
  root 'home#index'


  # resources :home
  resources :chart do
    collection do
      get '/', to: 'chart#index', as: 'analysis'
      # post '/analysis/:analysis_id', to: 'chart#analysis'
      get '/analysis/:analysis_id', to: 'chart#analysis'
    end
  end

  resources :map
  resources :users
  resources :turtles
  resources :turtle_data
  resources :sessions

  get 'map/turtle_info/:id',controller: 'turtles', action: 'turtle_info', as: 'turtle_info'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  get 'home', to: 'home#index', as: 'home'
  # get 'chart', to: 'chart#chart', as: 'chart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base

    validates :email, 
      :presence => :true,
      :format => { 
        :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
        :message => "must be a valid email address"
      }
    validates :message, :presence => :true
    validates :name, :presence => :true
  
  end

app/models/turtle.rb
class Turtle < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    # validates :user_id, presence: true
    validates :species, presence: true

    belongs_to :user
    has_many :turtle_data, dependent: :destroy

    def self.search(search)
        if search.present?
            Turtle.where('name LIKE ?', "%#{search}%")
        else
            Turtle.all
        end
      end  
end

app/models/turtle_datum.rb
class TurtleDatum < ApplicationRecord
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :turtle, presence: true

  belongs_to :turtle

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  has_secure_password


  validates :email, presence: true, uniqueness: true, :format => { 
    :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    :message => "must be a valid email address"
  }

 

  validates :occupation, presence: true
  validates :institution, presence: true

  has_many :turtles, dependent: :destroy

  def self.search(search)
    if search.present?
        User.where("name LIKE ? OR Institution LIKE ? OR email LIKE ?", "%#{search}%","%#{search}%", "%#{search}%")
    else
        User.all
    end
  end  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/chart_controller.rb
class ChartController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout 'application'

  def index
  end

  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.js { head :ok }
    end
  end

 
  def analysis
    @data = User.all.select(:id,:institution) 
    
    logger.info(params[:analysis_id])
    if params[:analysis_id] == '1'
      @type = 'bars'

    elsif params[:analysis_id] == '2'
      @type = 'dount'

      
    elsif params[:analysis_id] == '3'
      @type = 'lines'
    elsif params[:analysis_id] == '4'
      @data = Turtle.all.select(:id,:species,:institution)
      @type = 'dount2'
    else
      @type = 'lines'
    end
    # @data = User.all.select(:id,:name)
    respond_to do |format|

      format.html { render partial: 'chart' }

    end
  end

   # def analysis
  #   logger.info(params[:analysis_id])
  #   if params[:analysis_id] == '1'
  #     @data = User.all.select(:id)
  #   elsif params[:analysis_id] == '2'
  #     @data = User.all.select(:id, :institution)
  #   else
  #     @data = User.all.select(:id, :name)
  #   end
  #   # @data = User.all.select(:id,:name)
  #   respond_to do |format|

  #     # format.html { render :test }
  #     format.json { render json: @data }

  #   end
  # end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # load_turtles
    @turtles = Turtle.all
    @users = User.all
    @turtleDatas = TurtleDatum.all
  end

  # def load_turtles  
  #   @turtles_default = Gmaps4rails.build_markers(Turtles.all) do |plot, marker|  
  #      marker.lat plot.latitude  
  #      marker.lng plot.longitude  

  #      @status = rand(1..4)  
  #      @battery = rand(10..90)  
  #      @ip = "192.168."+rand(0..255).to_s+"."+rand(15..250).to_s  
  #      @connected = rand(50..100)  

  #      if @status == 1  
  #        url_alert = "/good.png"  
  #        @status == "Normal"  
  #      else  
  #        url_alert = "/alert.png"  
  #      end  

  #      marker.picture({  
  #        "url" => url_alert,  
  #        "width" => 35,  
  #        "height" => 30  
  #      })  

  #      marker.infowindow render_to_string(:partial => "/turtles/info",   
  #        :locals => {:name => plot.name, :battery => @battery, :date => rand(6.months.ago..Time.now), :ip => @ip, :connected => @connected })  
  #   end  
  # end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    # load_turtles
    @turtles = Turtle.all
  end
  
  # def load_turtles  
  #   @turtles_default = Gmaps4rails.build_markers(Turtles.all) do |plot, marker|  
  #      marker.lat plot.latitude  
  #      marker.lng plot.longitude  
 
  #      @status = rand(1..4)  
  #      @battery = rand(10..90)  
  #      @ip = "192.168."+rand(0..255).to_s+"."+rand(15..250).to_s  
  #      @connected = rand(50..100)  
 
  #      if @status == 1  
  #        url_alert = "/good.png"  
  #        @status == "Normal"  
  #      else  
  #        url_alert = "/alert.png"  
  #      end  
 
  #      marker.picture({  
  #        "url" => url_alert,  
  #        "width" => 35,  
  #        "height" => 30  
  #      })  
 
  #      marker.infowindow render_to_string(:partial => "/turtles/info",   
  #        :locals => {:name => plot.name, :battery => @battery, :date => rand(6.months.ago..Time.now), :ip => @ip, :connected => @connected })  
  #   end  
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/turtle_data_helper.rb
module TurtleDataHelper
end

app/helpers/turtles_helper.rb
module TurtlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>IOTSite</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path('icon_turtle.png'), :rel => 'icon', :type =>  'image/png' %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <meta charset="utf-8">

  <!-- d3 -->
  <script src="https://d3js.org/d3.v4.js"></script>
  <script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
  <script src="https://kit.fontawesome.com/a321da4d29.js" crossorigin="anonymous"></script>

  <!-- Google maps -->

  <script src="//maps.google.com/maps/api/js?key=AIzaSyD25cDQ6SX_v1Kz1MDBf-PJsgLB38B83T4"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js'
    type='text/javascript'></script>
  <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>



  <!-- <script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
<script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script> -->

</head>

<body>
<%#= image_tag("fishUnderwater.jpg", :class => "bg", :style => "") %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <a class="navbar-brand" href=<%= home_path %>>I<i class="fas fa-globe-americas fa-xs"></i>T</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href=<%=home_path %>>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=analysis_chart_index_path%>>Analysis</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=map_index_path %>>Interactive Map</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=about_index_path %>>About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=new_contact_path %>>Contact</a>
        </li>
      </ul>

      <%= form_tag search_result_path, :method => :get, :class => "form-inline my-2 my-lg-0 ml-auto" do %>
      <%= text_field_tag :search_text ,params[:search_text] , :class => "form-control mr-sm-2" %>
      <%= submit_tag 'Search' , :class => "btn btn-outline-info my-2 my-sm-0" %>
      <% end %>



      <br>
      <% if current_user %>
      <ul class="navbar-nav ml-0">
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">

            <% if current_user.image.attached? %>
            <img class="img-thumbnail" style="width:30px;margin-right: 10px;"
              src="<%= (url_for(current_user.image)) %>">
            <% else %>
            <%= image_tag("defaultProfile.png", :class => "img-thumbnail", :style => "width:30px;margin-right: 10px") %>
            <!-- <image src="defaultProfile.png"> -->
            <% end %><%= current_user.name %>
            <span class="caret"></span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href=<%= edit_user_path(current_user) %>>Profile</a>
            <a class="dropdown-item" href=<%= logout_path %>>Sign Out</a>
          </div>

        </li>
      </ul>
      <% else %>
      <ul class="navbar-nav ml-0 ">
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-cog fa-xs"></i> Sign in
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href=<%= login_path %>>Sign in</a>
            <a class="dropdown-item" href=<%= signup_path %>>Sign up</a>
          </div>
        </li>
      </ul>
      <% end %>
    </div>
  </nav>


<div class="content">
  <%= yield %></br>
</div>

  <!-- Footer -->
  <footer class="page-footer font-small bg-light footer">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a class="text-info" href="http://www.lsi.usp.br/citi/"> Citi-USP</a>
    </div>
    <!-- Copyright -->

  </footer>

  <script>
    function search() {
      var search_text = document.getElementById('search_field').value;
      // var search_text = $(this).data('search_field');
      console.log(search_text);
      if (search_text) {
        window.location = '/player_detail?search_text=' + search_text;
      }
    }
  </script>
<script>
    $(function(){
        $('a').each(function(){
            if ($(this).prop('href') == window.location.href) {
                $(this).addClass('active'); $(this).parents('li').addClass('active');
            }
        });
    });
</script>
</body>

</html>